/*
 * Copyright 2019 junichi11.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.netbeans.modules.php.cake3.ui.customizer;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.awt.Mnemonics;
import org.openide.util.ChangeSupport;
import org.openide.util.NbBundle;

/**
 *
 * @author junichi11
 */
public class CakePHP3CustomizerPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -4175785695400750924L;

    private final ChangeSupport changeSupport = new ChangeSupport(this);

    /**
     * Creates new form CakePHP3CustomizerPanel
     */
    public CakePHP3CustomizerPanel() {
        initComponents();
        init();
    }

    private void init() {
        // add DocumentListener
        DefaultDocumentListener documentListener = new DefaultDocumentListener();
        rootTextField.getDocument().addDocumentListener(documentListener);
        srcTextField.getDocument().addDocumentListener(documentListener);
        wwwRootTextField.getDocument().addDocumentListener(documentListener);
        cssTextField.getDocument().addDocumentListener(documentListener);
        imgTextField.getDocument().addDocumentListener(documentListener);
        jsTextField.getDocument().addDocumentListener(documentListener);
        dotcakeTextField.getDocument().addDocumentListener(documentListener);
        enabledCheckBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                fireChange();
            }
        });
    }

    public void setCakePHP3Enabled(boolean isEnabled) {
        enabledCheckBox.setSelected(isEnabled);
        setAllComponentsEnabled(isEnabled);
    }

    public boolean isCakePHP3Enabled() {
        return enabledCheckBox.isSelected();
    }

    public String getNamespace() {
        return namespaceTextField.getText().trim();
    }

    public void setNameSpace(String namespace) {
        namespaceTextField.setText(namespace);
    }

    public String getRoot() {
        return rootTextField.getText().trim();
    }

    public void setRoot(String root) {
        rootTextField.setText(root);
    }

    public String getSrc() {
        return srcTextField.getText().trim();
    }

    public void setSrc(String src) {
        srcTextField.setText(src);
    }

    public String getWWWRoot() {
        return wwwRootTextField.getText().trim();
    }

    public void setWWWRoot(String wwwRoot) {
        wwwRootTextField.setText(wwwRoot);
    }

    public String getCss() {
        return cssTextField.getText().trim();
    }

    public void setCss(String css) {
        cssTextField.setText(css);
    }

    public String getJs() {
        return jsTextField.getText().trim();
    }

    public void setJs(String js) {
        jsTextField.setText(js);
    }

    public String getImg() {
        return imgTextField.getText().trim();
    }

    public void setImg(String img) {
        imgTextField.setText(img);
    }

    public String getDotcakePath() {
        return dotcakeTextField.getText().trim();
    }

    public void setDotcakePath(String path) {
        dotcakeTextField.setText(path);
    }

    private void setAllComponentsEnabled(boolean isEnabled) {
        Component[] components = getComponents();
        for (Component component : components) {
            if (component == enabledCheckBox || component == enabledMessageLabel || component == generalLabel) {
                continue;
            }
            component.setEnabled(isEnabled);
        }
    }

    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }

    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    void fireChange() {
        changeSupport.fireChange();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalLabel = new JLabel();
        enabledCheckBox = new JCheckBox();
        enabledMessageLabel = new JLabel();
        pathSettingsLabel = new JLabel();
        wwwRootLabel = new JLabel();
        wwwRootTextField = new JTextField();
        cssLabel = new JLabel();
        cssTextField = new JTextField();
        jsLabel = new JLabel();
        jsTextField = new JTextField();
        imgLabel = new JLabel();
        imgTextField = new JTextField();
        rootLabel = new JLabel();
        rootTextField = new JTextField();
        srcLabel = new JLabel();
        srcTextField = new JTextField();
        namespaceLabel = new JLabel();
        namespaceTextField = new JTextField();
        dotcakeLabel = new JLabel();
        dotcakeTextField = new JTextField();

        Mnemonics.setLocalizedText(generalLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.generalLabel.text")); // NOI18N

        Mnemonics.setLocalizedText(enabledCheckBox, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.enabledCheckBox.text")); // NOI18N
        enabledCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                enabledCheckBoxActionPerformed(evt);
            }
        });

        Mnemonics.setLocalizedText(enabledMessageLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.enabledMessageLabel.text")); // NOI18N

        Mnemonics.setLocalizedText(pathSettingsLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.pathSettingsLabel.text")); // NOI18N

        Mnemonics.setLocalizedText(wwwRootLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.wwwRootLabel.text")); // NOI18N

        wwwRootTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.wwwRootTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(cssLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.cssLabel.text")); // NOI18N

        cssTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.cssTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(jsLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.jsLabel.text")); // NOI18N

        jsTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.jsTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(imgLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.imgLabel.text")); // NOI18N

        imgTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.imgTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(rootLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.rootLabel.text")); // NOI18N

        rootTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.rootTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(srcLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.srcLabel.text")); // NOI18N

        srcTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.srcTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(namespaceLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.namespaceLabel.text")); // NOI18N

        namespaceTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.namespaceTextField.text")); // NOI18N

        Mnemonics.setLocalizedText(dotcakeLabel, NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.dotcakeLabel.text")); // NOI18N

        dotcakeTextField.setText(NbBundle.getMessage(CakePHP3CustomizerPanel.class, "CakePHP3CustomizerPanel.dotcakeTextField.text")); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(enabledCheckBox))
                            .addComponent(generalLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(enabledMessageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(pathSettingsLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(wwwRootLabel)
                                            .addComponent(rootLabel)
                                            .addComponent(srcLabel)))
                                    .addComponent(namespaceLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(cssLabel)
                                    .addComponent(imgLabel)
                                    .addComponent(jsLabel))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(wwwRootTextField, GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(cssTextField)
                            .addComponent(rootTextField)
                            .addComponent(srcTextField)
                            .addComponent(namespaceTextField)
                            .addComponent(imgTextField)
                            .addComponent(jsTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dotcakeLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dotcakeTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enabledCheckBox)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enabledMessageLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(namespaceLabel)
                    .addComponent(namespaceTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pathSettingsLabel)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(rootLabel)
                    .addComponent(rootTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(srcLabel)
                    .addComponent(srcTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwRootLabel)
                    .addComponent(wwwRootTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cssTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cssLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(imgLabel)
                    .addComponent(imgTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jsLabel)
                    .addComponent(jsTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dotcakeLabel)
                    .addComponent(dotcakeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enabledCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_enabledCheckBoxActionPerformed
        setAllComponentsEnabled(isCakePHP3Enabled());
    }//GEN-LAST:event_enabledCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel cssLabel;
    private JTextField cssTextField;
    private JLabel dotcakeLabel;
    private JTextField dotcakeTextField;
    private JCheckBox enabledCheckBox;
    private JLabel enabledMessageLabel;
    private JLabel generalLabel;
    private JLabel imgLabel;
    private JTextField imgTextField;
    private JLabel jsLabel;
    private JTextField jsTextField;
    private JLabel namespaceLabel;
    private JTextField namespaceTextField;
    private JLabel pathSettingsLabel;
    private JLabel rootLabel;
    private JTextField rootTextField;
    private JLabel srcLabel;
    private JTextField srcTextField;
    private JLabel wwwRootLabel;
    private JTextField wwwRootTextField;
    // End of variables declaration//GEN-END:variables

    //~ Inner class
    private class DefaultDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            processUpdate();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            processUpdate();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            processUpdate();
        }

        private void processUpdate() {
            fireChange();
        }

    }
}
